### ISSUE TITLE
 Redis connection failed after installing docker

### ISSUE THREAD

**Issue by huanglong** [NodeBB/docker-builds#1]
When I run Nodebb:

```
docker run --name nodebb --link nodebb-redis:redis -p 80:80 -p 443:443 -p 4567:4567 -P -t -i nodebb/docker:ubuntu
```

I got:

```
docker run --name nodebb --link nodebb-redis:redis -p 80:80 -p 443:443 -p 4567:4567 -P -t -i nodebb/docker:ubuntu
3/5 15:28 [1] - info: NodeBB v0.6.1 Copyright (C) 2013-2014 NodeBB Inc.
3/5 15:28 [1] - info: This program comes with ABSOLUTELY NO WARRANTY.
3/5 15:28 [1] - info: This is free software, and you are welcome to redistribute it under certain conditions.
3/5 15:28 [1] - info:
3/5 15:28 [1] - warn: Configuration not found, starting NodeBB setup
3/5 15:28 [1] - info: Welcome to NodeBB!
3/5 15:28 [1] - info: This looks like a new installation, so you'll have to answer a few questions about your environment before we can proceed.
3/5 15:28 [1] - info: Press enter to accept the default setting (shown in brackets).
URL used to access this NodeBB (http://localhost:4567)
Please enter a NodeBB secret (03c99b8d-ff9f-4ae2-9b23-514426828b56)
Which database to use (redis) redis

3/5 15:29 [1] - info: Now configuring redis database:
Host IP or address of your Redis instance (127.0.0.1)
Host port of your Redis instance (6379)
Password of your Redis database
Which database to use (0..n) (0)
3/5 15:29 [1] - info: Configuration Saved OK
npm WARN package.json nodebb-plugin-dbsearch@0.1.1 No repository field.
redis@0.10.3 node_modules/redis

connect-redis@2.0.0 node_modules/connect-redis
└── debug@2.1.3 (ms@0.7.0)
3/5 15:29 [1] - info: Populating database with default configs, if not already set...
3/5 15:29 [1] - error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.flush_and_error (/opt/nodebb/node_modules/redis/index.js:142:13)
    at RedisClient.on_error (/opt/nodebb/node_modules/redis/index.js:180:10)
    at Socket.<anonymous> (/opt/nodebb/node_modules/redis/index.js:95:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
3/5 15:29 [1] - warn: NodeBB Setup Aborted. Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
```

How can I solve this, Thanks~

**Comment by huanglong** [comment]
Solved by config the Host IP:

```
Host IP or address of your Redis instance (127.0.0.1) redis
```
